#!/bin/bash

#set -x

if [ $# -ne 1 ]; then
  echo 1>&2 "Usage: build <version>"
  echo 1>&2 "    <version> Version of this release"
  exit 1
fi
VERSION=$1
DESTDIR=configuration/config

tarballname="lots-config-${VERSION}"
tarball="${tarballname}.tar.gz"
zipball="lots-config-${VERSION}.7z"

rm -f ${tarball} ${zipball} .lots/config/plugins/classes.jar .lots/config/plugins/*.class
javac --release 8 -verbose .lots/config/plugins/de/muenchen/allg/itd51/wollmux/func/*.java
javac --release 8 -verbose .lots/config/plugins/de/muenchen/allg/d101/*.java
(cd .lots/config/plugins && jar cvf ./classes.jar \
	de/muenchen/allg/itd51/wollmux/func/*.class \
	de/muenchen/allg/d101/*.class )

echo 'Build tar'
tar --owner=0 --group=0 -czf "${tarball}" .lots
echo 'Build 7z'
${DESTDIR}/scripts/tarTo7z "${tarball}"
